# Generated by Django 5.2.5 on 2025-08-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="buffer_time",
            field=models.DecimalField(
                decimal_places=2,
                default=0.16,
                help_text="Buffer time for delays in hours (e.g., 0.16 for 10 minutes)",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="duration",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Duration of the trip in hours (e.g., 1.5 for 1 hour 30 minutes)",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="turnaround_time",
            field=models.DecimalField(
                decimal_places=2,
                default=0.33,
                help_text="Turnaround time at terminal in hours (e.g., 0.33 for 20 minutes)",
                max_digits=4,
            ),
        ),
    ]
