# Generated by Django 5.2.5 on 2025-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_route_buffer_time_route_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="is_limited_stop",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is a major stop served by limited stop buses",
            ),
        ),
    ]
