# Generated by Django 5.2.5 on 2025-08-31 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0002_route_buffer_time_route_duration_and_more"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(
                        help_text="The start date (Monday) of the week being recorded."
                    ),
                ),
                (
                    "total_passengers",
                    models.PositiveIntegerField(
                        help_text="Total passengers carried on this route this week."
                    ),
                ),
                (
                    "total_kms",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total kilometers traveled this week.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated revenue: total_passengers * ticket_price.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated cost: (total_kms / bus.mileage) * fuel_price.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated profit: total_revenue - total_cost.",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_performances",
                        to="schedules.bus",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_performances",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start_date", "bus"],
                "unique_together": {("bus", "route", "week_start_date")},
            },
        ),
    ]
