# Generated by Django 5.2.5 on 2025-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_alter_weeklyperformance_total_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyperformance",
            name="actual_passengers",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Actual passengers from ticket sales (manually entered)",
            ),
        ),
        migrations.AddField(
            model_name="weeklyperformance",
            name="estimated_passengers",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Estimated passengers from PreInform data (auto-calculated)",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyperformance",
            name="total_passengers",
            field=models.PositiveIntegerField(
                help_text="Total passengers carried on this route this week. Auto-calculated from estimated + actual."
            ),
        ),
    ]
