# Generated by Django 5.2.5 on 2025-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="mileage",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Mileage in km/liter",
                max_digits=5,
            ),
        ),
    ]
