# Generated by Django 5.2.5 on 2025-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_bus_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("all_stop", "All Stop Service"),
                    ("limited_stop", "Limited Stop Service"),
                    ("express", "Express Service"),
                ],
                default="all_stop",
                max_length=20,
            ),
        ),
    ]
