# Generated by Django 5.2.5 on 2025-08-31 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_stop_is_limited_stop"),
        ("schedules", "0003_bus_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="current_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_buses",
                to="routes.route",
            ),
        ),
    ]
