# Generated by Django 5.2.5 on 2025-08-31 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_stop_is_limited_stop"),
        ("schedules", "0004_bus_current_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="current_route",
        ),
        migrations.CreateModel(
            name="BusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the assignment")),
                (
                    "start_time",
                    models.TimeField(help_text="When the bus starts this route"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="When the bus finishes this route"),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_schedules",
                        to="schedules.bus",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_schedules",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Assignment",
                "verbose_name_plural": "Bus Assignments",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
