# Generated by Django 5.2.5 on 2025-09-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_stop_is_limited_stop"),
        ("schedules", "0005_remove_bus_current_route_busschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="current_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Current GPS latitude",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="current_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Current GPS longitude",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="current_route",
            field=models.ForeignKey(
                blank=True,
                help_text="Route currently being served",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="routes.route",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="current_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Current active schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_buses",
                to="schedules.schedule",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="is_running",
            field=models.BooleanField(
                default=False, help_text="Is bus currently on route"
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="last_location_update",
            field=models.DateTimeField(
                blank=True, help_text="When location was last updated", null=True
            ),
        ),
    ]
