# Generated by Django 5.2.5 on 2025-09-05 01:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_bus_current_latitude_bus_current_longitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="current_schedule",
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={
                ("bus", "date", "departure_time"),
                ("driver", "date", "departure_time"),
            },
        ),
    ]
